steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gsutil', 'cp', '-r', 'gs://comments-app', '.']
    waitFor: ['-']
    id: 'pull-config'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/comments-app:$SHORT_SHA', '.']
    waitFor: ['pull-config']
    id: 'build-image'
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        'container',
        'clusters',
        'get-credentials',
        'ben-site-prod',
        '--region',
        'asia-east1-c',
      ]
    id: 'prepare-credentials'
  - name: 'gcr.io/$PROJECT_ID/helm'
    args:
      [
        '--namespace=sandbox',
        'upgrade',
        '--install',
        'comments-app',
        'comments-app',
        '-f',
        'comments-app/values.yaml',
        '--set',
        'image.tag=$SHORT_SHA',
      ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ben-site-prod'
    waitFor: ['build-image', 'pull-config', 'prepare-credentials']
tags: ['cloud-builders-community']
images: ['gcr.io/$PROJECT_ID/comments-app']
